name: Build Flutter APK

on:
  push:
    branches:
      - eded
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Java 17
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      # Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: stable
          cache: true

      # Cek Java
      - name: Check Java
        run: |
          java -version
          echo "JAVA_HOME=$JAVA_HOME"

      # Cek Flutter
      - name: Check Flutter
        run: flutter doctor -v

      # Install dependencies
      - name: Flutter Pub Get
        run: flutter pub get

      # Build APK
      - name: Build APK
        run: flutter build apk --release

      # Upload APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error
